### ISSUE TITLE
Is display of archive programmes supported?

### ISSUE THREAD

**Issue by Krupek20** [tomzox/nxtvepg#2]
Hi,

I tried, and it seems the program correctly parses the archive data (programmes with start date earlier than today) - it shows statistics how much of data is old -  but I haven't find any way to display archive data. I would like to display it and be able to filter it the same way as current/future data.

Is it possible?

Thank you.

**Comment by tomzox** [comment]
Sorry for the long response time. (Apparently I didn't have the right notifications enabled at GitHub.) I was surprised myself to find that nxtvepg does not allow displaying expired programmes once all items in the database are expired. There's a filter for expiry control, but it allows to shift it by at most 7 days.

I've uploaded a fix for this. There's now two ways: In Filter -> "Expired display" check button "Show all expired programmes". Or open Control -> "View coverage timescales" and click on any of the time-scale bars.

Hope that still helps.

**Comment by Krupek20** [comment]
Can you please release a new version (nxtvepg-3.X.X-win-setup.exe) in https://nxtvepg.sourceforge.net/download.html so I can check the fix?

**Comment by tomzox** [comment]
I uploaded a debug release: https://nxtvepg.sourceforge.net/tmp/nxtvepg-3.0.1-win.zip

It's a plain ZIP archive without installer. Either unpack to an empty directory and run "nxtvepg.exe", or extract the executable file into the regular installation directory. Once you confirm the solution is good for you, I can make a regular release. If not, please let me know more about your use case or suggest how it needs to be improved.

**Comment by Krupek20** [comment]
I confirm that both ways of showing archive data, mentioned by you previously, work correctly.

PS. I registered a new issue: "Is showing and filtering by "category", "rating", "star-rating" or "actor"(s) possible?" that describe my further problems with nxtvepg. Please review at your earliest convenience.
